- model: "模式: 标准"
  onlyCookies: "筛选请求头:Cookie,X-Csrf-Token"

- model: "模式: 自动更新token"
  onlyCookies: "筛选请求头:Cookie,X-Csrf-Token"
  1:
    status: 400
    body:
    - 'csrf'
    request: "./config/https_update_token.txt"
    get_token:
      status: 200
      value: "X-Csrf-Token"
      where: "json.loads(Tres.text)['token']" #dict(res.headers)['X-Csrf-Token']